import { LOCALES } from './constants';

export default {
  [LOCALES.ru]: {
    mole: 'моль',
    moleK: '(моль×K)',
    melt: 'распл.',
    sol: 'р-ра',
    g: 'г',
    gmole: 'г/моль',
    gdm: 'г/дм',
    mg: 'мг',
    kg: 'кг',
    l: 'л',
    k: 'K',
    units: 'единиц',
    air: 'возд.',
    atom: 'атома',
    fraction: 'доля',
    dm: 'дм',
    dm3: 'дм3',
    mix: 'смеси',
    aem: 'а.е.м.',
    entities: 'частиц',
    yield: 'вых.',
    theor: 'теор.',
    pract: 'практ.',
    kpa: 'кПа',
    j: 'Дж',
    water: 'воды',
    find: 'Найти',
    example: 'Например:',
    examples: 'Другие примеры:',
    subs: 'в-ва',
    to: 'по',
    ore: 'руды',
    inputDataError: 'Проверьте правильность ввода.',
    wrongBraces: 'Неправильно расставлены скобки.',
    bigLetterError: 'Каждый элемент должен начинаться с заглавной буквы.',
    failedSetOdds: 'Не удалось расставить коэффициенты',
    equationNotExist: 'Возможно, уравнение не существует',
    wrongEquation: 'Неправильное уравнение',
    success: 'Успех',
    error: 'Ошибка',
    networkError:
      'Произошла ошибка инициализации. Включите, пожалуйста, интернет.',
    initSuccess: 'Инициализация прошла успешно.',
    unknownError: 'Произошла неизвестная ошибка.',
  },
  [LOCALES.en]: {
    mole: 'mole',
    moleK: '(mole×K)',
    melt: 'melt.',
    sol: 'sol.',
    g: 'g',
    gmole: 'g/mole',
    gdm: 'g/dm',
    mg: 'mg',
    kg: 'kg',
    l: 'l',
    k: 'K',
    units: 'units',
    air: 'air',
    atom: 'atom',
    fraction: 'fraction',
    dm: 'dm',
    dm3: 'dm3',
    mix: 'mix',
    aem: 'atomic mass unit',
    entities: 'of entities',
    yield: 'yield',
    theor: 'theor.',
    pract: 'pract.',
    kpa: 'kPa',
    j: 'J',
    water: 'water',
    find: 'Find',
    example: 'For example:',
    examples: 'Other examples:',
    subs: 'subs.',
    to: 'to',
    ore: 'ore',
    inputDataError: 'Check the input.',
    wrongBraces: 'Incorrect arrangement of parentheses.',
    bigLetterError: 'Every element should start with capital letter.',
    failedSetOdds: 'Unable to arrange the coefficients',
    equationNotExist: "Probably, the equation doesn't exist",
    wrongEquation: 'Incorrect equation',
    success: 'Success',
    error: 'Error',
    networkError:
      'Initialization error occurred. Please check internet connection.',
    initSuccess: 'Success initialized.',
    unknownError: 'Unknown error occurred.',
  },
};
