import { SectionsType } from '../features/cheats/constants';

export enum SCREENS {
  HOME = 'HOME',
  REACTIVITY = 'REACTIVITY',
  FORMULAS = 'FORMULAS',
  PERIODIC_TABLE = 'PERIODIC_TABLE',
  SOLUBILITY_TABLE = 'SOLUBILITY_TABLE',
  REACTIONS = 'REACTIONS',
  CHAINS = 'CHAINS',
  MOLAR_MASSES = 'MOLAR_MASSES',
  COEF_ARRANGEMENT = 'COEF_ARRANGEMENT',
  TASK_SOLVER_REACTION_QUESTION = 'TASK_SOLVER_REACTION_QUESTION',
  TASK_SOLVER_SUBSTANCE_QUESTION = 'TASK_SOLVER_SUBSTANCE_QUESTION',
  TASK_SOLVER_REACTION_FIND = 'TASK_SOLVER_REACTION_FIND',
  TASK_SOLVER_SUBSTANCE_ENTER = 'TASK_SOLVER_SUBSTANCE_ENTER',
  TASK_SOLVER_REACTION_ENTER = 'TASK_SOLVER_REACTION_ENTER',
  TASK_SOLVER_PROBLEM_GIVEN = 'TASK_SOLVER_PROBLEM_GIVEN',
  TASK_SOLVER_PROBLEM_FIND = 'TASK_SOLVER_PROBLEM_FIND',
  TASK_SOLVER_SOLUTION = 'TASK_SOLVER_SOLUTION',
  CHEATS_MAIN = 'CHEATS_MAIN',
  CHEATS_LIST = 'CHEATS_LIST',
  CHEATS_ARTICLE = 'CHEATS_ARTICLE',
}

export const getCheatsTitle = (section: SectionsType) =>
  section === 'ORGANIC' ? 'title_organic' : 'title_inorganic';
